Setup sections for copy
includebraga/website pull request #5
Opened 2018-04-23 22:54 UTC by fribmendes

2018-04-23 23:00 UTC, jfranciscosousa requested changes
Remove `yarn.lock` we run `npm` in this project. Also don't forget to lint with `npm run lint-fix` and `npm run lint-styles-fix` if needed.

2018-04-24 13:18 UTC, jfranciscosousa commented
@fribmendes want to change spacings after or in this PR?

2018-04-24 13:30 UTC, fribmendes commented
After this PR

2018-04-24 13:31 UTC, jfranciscosousa commented
@luisptorres will style this when he finds some time for it.

2018-04-24 13:32 UTC, jfranciscosousa requested changes

2018-04-24 13:32 UTC, jfranciscosousa commented on src/sections/Contact/index.js
> +export default function Contact() {
Useless section. Add the missing `mail` contact to the `SocialLinks` component,

2018-04-24 13:33 UTC, jfranciscosousa commented on src/sections/Contact/index.js
> +export default function Contact() {
`Footer` component, my mistake.

2018-04-24 13:35 UTC, nelsonmestevao commented
@fribmendes, my name is Nelson Estevão :stuck_out_tongue_winking_eye:

2018-04-25 10:43 UTC, fribmendes commented
@luisptorres I'd rather not keep this on hold waiting for you. I suggest merging right away and you can add style on a different PR

2018-04-25 10:45 UTC, fribmendes commented
@jfranciscosousa @nelsonmestevao all done 👍

2018-04-25 21:18 UTC, jfranciscosousa approved these changes

2018-04-26 09:23 UTC, merged